# Generated by Django 6.0.6 on 2026-06-20 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField()),
                ('nom', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('poste', models.CharField(max_length=100)),
                ('salaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dateNaissance', models.DateField()),
                ('numero', models.IntegerField()),
            ],
        ),
    ]
